- hosts: all
  become: yes
  tasks:
  
    - name: Creating LXD container
      lxd_container:
        name: "{{ item }}"
        state: started
        cert_file:  lxd-api-access-cert-key-files/lxd-webui.crt
        config:
          limits.cpu: "2"
          limits.memory: 4GB
          limits.memory.swap: "false"
          linux.kernel_modules: bridge,br_netfilter,x_tables,ip_tables,ip6_tables,ip_vs,ip_set,ipip,xt_mark,xt_multiport,ip_tunnel,tunnel4,nf_conntrack,nfnetlink,netlink_diag,nf_nat,overlay
          raw.lxc: "lxc.apparmor.profile=unconfined\nlxc.cap.drop= \nlxc.cgroup.devices.allow=a\nlxc.mount.auto=proc:rw sys:rw"
          security.nesting: "true"
          security.privileged: "true"
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: 19.04/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      with_items:
        - k8s-master
        - k8s-node-1
        - k8s-node-2
        
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash
    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=ubuntu key="{{item}}"
      with_file:
        - ~/.ssh/authorized_keys
